name: ci-workflow

on:
  workflow_dispatch:
  push:
    paths:
      - '**.h'
      - '**.cpp'
      - '**/CMakeList.txt'
      - '.github/workflows/ci-workflow.yml'
  pull_request:
    paths:
      - '**.h'
      - '**.cpp'
      - '**/CMakeList.txt'
      - '.github/workflows/ci-workflow.yml'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout Catch2 v3
      uses: actions/checkout@v4
      with:
          repository: catchorg/Catch2
          ref: v3.4.0
          path: Catch2

    - name: Install Catch2 v3
      run: |
        mkdir Catch2/build
        cd Catch2/build
        cmake .. -DBUILD_TESTING=OFF
        sudo cmake --build . --target install

    - name: test
      run: |
        mkdir test/build
        cd test/build
        cmake .. && make && ./test_spiritless_po

  windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout Catch2 v3
      uses: actions/checkout@v4
      with:
          repository: catchorg/Catch2
          ref: v3.4.0
          path: Catch2

    - name: Install Catch2 v3
      run: |
        mkdir Catch2/build
        cd Catch2/build
        cmake .. -DBUILD_TESTING=OFF
        cmake --build . --target install

    - name: build test
      run: |
        mkdir test/build
        cd test/build
        cmake .. && cmake --build .
