name: ci-workflow

on:
  workflow_dispatch:
  push:
    paths:
      - '**.h'
      - '**.cpp'
      - '**/CMakeList.txt'
      - '.github/workflow/ci-workflow.yml'
  pull_request:
    paths:
      - '**.h'
      - '**.cpp'
      - '**/CMakeList.txt'
      - '.github/workflow/ci-workflow.yml'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: apt-get install catch2
      run: sudo apt-get -y install catch2

    - name: test
      run: |
        mkdir test/build
        cd test/build
        cmake .. && make && ./test_spiritless_po
